baseURL = 'https://sleepy-puppy-studios.github.io/royal-feast-devlog'
locale = 'en-us'
title = 'A Feast Most Deadly Devlog'
theme = 'hugo-paper'

[caches]
    [caches.images]
        dir = ':cacheDir/images'

[params]
name = 'Sleepy Puppy Studios'
bio = 'The dev team behind the upcoming game A Feast Most Deadly'
disablePostNavigation = false

[menu]
    [[menu.main]]
        name = 'Home'
        pageRef = '/'
        weight = 10
    [[menu.main]]
        name = 'About'
        pageRef = 'about.md'
        weight = 20